apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-broker
  namespace: message-broker
spec:
  selector:
    matchLabels:
      app: rabbit-broker
  template:
    metadata:
      labels:
        app: rabbit-broker
    spec:
      containers:
        - name: rabbit-broker
          image: rabbitmq:4.3.0-management-alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: 128Mi
              cpu: 200m  
          ports:
            - containerPort: 5672
            - containerPort: 15672
