apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-queue-worker
  namespace: async-queue
spec:
  selector:
    matchLabels:
      app: async-queue-worker
  replicas: 1
  template:
    metadata:
      labels:
          app: async-queue-worker
    spec:
      containers:
      - name: async-queue-worker 
        image: gcostacoelho/async-queue-worker
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
          requests:
            memory: 128Mi
            cpu: 200m
        envFrom:
          - configMapRef:
              name: async-queue-api-configmap
          - secretRef:
              name: app-secrets