apiVersion: v1
kind: ConfigMap
metadata:
  name: async-queue-api-configmap
  namespace: async-queue
data:
  DB_HOST: postgres-database-service.database.svc.cluster.local # - intern SVC URL
  DB_PORT: "5432"
  DB_NAME: async_queue_db
  RABBITMQ_HOST: rabbit.svc.cluster.local # - intern SVC URL
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: tasks
  API_PORT: "3000"
  NODE_ENV: development

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: async-queue-worker-configmap
  namespace: async-queue
data:
  DB_HOST: postgres-database-service.database.svc.cluster.local # - intern SVC URL
  DB_PORT: "5432"
  DB_NAME: async_queue_db
  RABBITMQ_HOST: rabbit.svc.cluster.local # - intern SVC URL
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: tasks
