name: ci-node

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node JS
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - run: "npm install"

  # Step de teste aqui (criar dps na aplicação)

  deploy-image:
    needs: build-app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-name: [api, worker]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: See project
        run: ls -a

      - name: Build and push image
        uses: docker/build-push-action@v7
        with: 
          file: ./Docker/Dockerfile.${{matrix.service-name}}
          context: .
          tags: "${{secrets.DOCKERHUB_USERNAME}}/async-queue-${{ matrix.service-name }}"
          push: true
