apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: message-broker
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/rabbitmq